version: '3.8'

services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://127.0.0.1:8010