application:
  config_path: "config.yaml"
  data_path: "./data/files"
  log_dir: "./data/app/logs"
  upload_subdir: "uploads"

qdrant_client_config:
  url: "http://localhost:6333"
  prefer_grpc: False

vector_store_config:
  collection_name: "test"
  vector_size: 384
  distance: Cosine

redis_config:
  host: "localhost"
  port: 6379

embedding:
  model: "local:BAAI/bge-small-en-v1.5"

llm:
  model: "llama3-chatqa"

reranker:
  model: "BAAI/bge-reranker-large"