version: '3.7'

services:
  es:
    image: docker.aiml.team/products/aiml/enterprise-search/llamasearch:latest
    volumes:
      - ./model_files:/app/model_files
      - ./config.yaml:/app/config.yaml  # Override the default config
      - ./eval_metrics_config.yaml:/app/eval_metrics_config.yaml
      - ./data/test_data:/data
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
