[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "llamasearch"
version = "0.1.0"
description = "LlamaSearch project"
requires-python = ">=3.9"

[tool.setuptools]
packages = ["llamasearch"]