apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi # For aiml-engineering, total storage quota right now is 30T
  storageClassName: longhorn