version: '3.8'
services:
  ollama:
      #image: ollama/ollama:latest
      image: ollama/ollama:0.3.6
      network_mode: host
      # ports:
      #   - 7869:11434
      volumes:
        - ./ollama/ollama:/root/.ollama
        - ./pull_models.sh:/pull_models.sh
        - ./entrypoint-ollama.sh:/entrypoint-ollama.sh
        - ../config/config.dev.yaml:/config.yaml
      container_name: ollama
      #pull_policy: always
      tty: true
      restart: always
      environment:
        - OLLAMA_KEEP_ALIVE=24h
        - OLLAMA_HOST=0.0.0.0
      entrypoint: ["/bin/sh", "/entrypoint-ollama.sh"]
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: all
                capabilities: [gpu]
      #systemctl stop ollama.service
      #sudo systemctl disable ollama.service