version: '3.7'

services:
  #ES Pipeline
  # es:
  #   image: docker.aiml.team/products/aiml/enterprise-search/llamasearch:latest
  #   container_name: enterprise_search
  #   volumes:
  #     - ./model_files:/app/model_files
  #     - ./config.yaml:/app/config.yaml  # Override the default config
  #     - ./data/:/data
  #   network_mode: host
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu]

  # # Vector Store
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_vector_store
    ports:
      - "6333:6333"
      - "6334:6334"
    restart: always
    environment:
      RUST_LOG: info

  # Document Store
  redis:
    container_name: redis_doc_store
    image: redis
    ports:
      - "6379:6379"
    restart: always