version: 1.0
metadata:
  author: "Deval Shah, Phil Roberts"
  last_modified: "2024-07-05"
  description: "Prompt to generate answer based on the query and context"
model:
  name: "llama3:8b"
  # format: "json"
  options:
    temperature: 0.3 # controlling the randomness of the responses.
    num_predict: 256
    num_ctx: 8192
    top_k: 20 # Reduces the probability of generating nonsense.
    top_p: 0.7
  stream: false
  raw: true
  #keep_alive: "5m" # Configures how long the model remains loaded in memory after a request.
  system: "You are a helpful AI assistant that gives precise answers based on the user provided context." #"system message to (overrides what is defined in the Modelfile)"
  #context: the context parameter returned from a previous request to /generate, this can be used to keep a short conversational memory
prompts:
  - role: user
    text: >
      Based on the provided context, please generate a direct answer to the posed query.

      ===== START OF EXAMPLE ======
      Example:
      Example Query:
      "Which authors have expertise in information retrieval?"

      Example Context:

      Title:
      Information Retrieval: Recent Advances and Beyond

      Authors:
      Kailash Hambarde, and Hugo Proença

      Excerpt:
      In this paper, we provide a detailed overview of the models used for information retrieval
      in the first and second stages of the typical processing chain. We discuss the current state-of-the-art
      models, including methods based on terms, semantic retrieval, and neural. Additionally, we delve
      into the key topics related to the learning process of these models. This way, this survey offers a
      comprehensive understanding of the field and is of interest for for researchers and practitioners
      entering/working in the information retrieval domain.

      Example Response:
      Kailash Hambarde, and Hugo Proença have expertise in information retrieval
      ===== END OF EXAMPLE ======

      **
      IMPORTANT: Please ensure the responses are in raw format. No additional words or explanations are needed.
      Only include responses that are factual and directly relevant to the query, using the full context provided by the retrieved documents.
      Align your response with context.
      If the provided context does not sufficiently answer the query, respond with: 'I am unable to answer due to insufficient context.'
      **
    type: text
