apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prometheus-service
  namespace: aiml-engineering
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
    - port: {{ .Values.prometheus.service.port }}
      targetPort: {{ .Values.prometheus.service.port }}
      nodePort: {{ .Values.prometheus.service.nodePort }}
  selector:
    app: {{ .Release.Name }}-prometheus