{{- if .Values.qdrant.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      # nodeSelector:
      #     #kubernetes.io/hostname: {{ .Values.qdrant.nodeName }}
      #     nvidia.com/gpu.product: {{ .Values.qdrant.gpuProduct }}
      containers:
      - name: qdrant
        image: "{{ .Values.qdrant.image.repository }}:{{ .Values.qdrant.image.tag }}"
        ports:
        - containerPort: {{ .Values.qdrant.service.port }}
        resources:
          limits:
            # nvidia.com/gpu: {{ index .Values.qdrant.resources.limits "nvidia.com/gpu" }}
            cpu: {{ .Values.qdrant.resources.limits.cpu }}
            memory: {{ .Values.qdrant.resources.limits.memory }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.qdrant.service.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 6
          successThreshold: 1
{{- end }}