apiVersion: batch/v1
kind: Job
metadata:
  name: qdrant-collection-creation
spec:
  backoffLimit: 10
  ttlSecondsAfterFinished: 100
  template:
    spec: 
      containers:
      - name: create-collection
        image: alpine/curl
        command: ["/bin/sh", "/scripts/create_collection.sh"]
        volumeMounts:
          - name: script
            mountPath: "/scripts"
          - name: config
            mountPath: "/app/config"
            readOnly: true
      restartPolicy: OnFailure
      volumes:
        - name: script
          configMap:
            name: {{ .Values.qdrant.volumes.script.configMapName }}
        - name: config
          configMap:
            name: {{ .Values.qdrant.volumes.config.configMapName }}