apiVersion: v1
kind: Service
metadata:
  name: qdrant-service
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.qdrant.service.port }}
      targetPort: {{ .Values.qdrant.service.port }}
      protocol: TCP
      name: qdrant
  selector:
    app: qdrant